### ISSUE TITLE
Extend/normalize crime/incarceration figure

### ISSUE THREAD

**Issue by mmiles19** [MKorostoff/incarceration-in-real-numbers#1]
Firstly, love this, thank you for making it. However the figure in which normalized crime rates are laid over total incarceration numbers is a little confusing. It seeks to highlight that reduction in crime rates are not correlated with incarceration rates. I think it would do so better by comparing normalized crime to normalized incarceration, as well as extending the timeline to before 1980 to include pre-mass incarceration as a control. Best!

**Comment by mkorostoff** [comment]
Can you clarify what you mean by "normalized"? I'm not a statistician (I'm a computer programmer; "normalized" means something very specific to me, but I feel like it's something different from how you're using it).

**Comment by derivator** [comment]
Normalization means "adjusting values measured on different scales to a notionally common scale", in this case "normalized" means "per capita". By using total incarceration instead of per capita, you leave yourself open to the argument that "it's just population growth", leaving it to the reader to figure out on their own that US population has grown by 44% since 1980, while according to your data, total incarceration has more than doubled.

Side note, that graph could also use a grid and some more intermediate years for easier comparisons.
