### ISSUE TITLE
Idea: Homeless people visualization

### ISSUE THREAD

**Issue by SMSadegh19** [MKorostoff/incarceration-in-real-numbers#11]
Hi Matt! @MKorostoff 
I think it can be a good idea to visualize homelessness data.
I thought about the "Street of homeless people" that people are visualized in a street...

And another question:
Where should we issue ideas and discuss **Scope insensitivity**?
You said it is your interest and you have an ongoing war on it!
I didn't know that where should I issue the new idea, So I issued it here.

+ [List of countries by homeless population](https://en.wikipedia.org/wiki/List_of_countries_by_homeless_population)
+ [Homelessness in the United States](https://en.wikipedia.org/wiki/Homelessness_in_the_United_States)

**Comment by mkorostoff** [comment]
Hi @SMSadegh19 I think it's a great idea, if you want to do this project I would be very excited to see it! I don't think I'm going to do any more visualization projects for a while, it's just gotten a little boring for me because I've done so many now, and I want to find a new kind of project where I can learn new skills.
